name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4.2.2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.11.1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Configure SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
    - name: Build and push
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

    - name: Delete old container
      continue-on-error: true
      run: |
        ssh -o StrictHostKeyChecking=no github@${{ secrets.SSH_SERVER_IP }} "sudo docker rm -f cinema-score && sudo docker rmi -f ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest"
        

    - name: Run new container
      run: |
        ssh -o StrictHostKeyChecking=no github@${{ secrets.SSH_SERVER_IP }} "sudo docker run -d --name cinema-score ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest"
        
